title: Latent Echo
description: A Case for Digital Sovereignty in AI Art
url: https://yourusername.github.io
baseurl: /latent-echo

# Build settings
markdown: kramdown
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock 